### ISSUE TITLE
Consistency across modules for parameter names

### ISSUE THREAD

**Issue by dado93** [dado93/pylabfront#38]
We need to have consistency across all the modules of pylabfront for the names of the parameters. Examples:

- sometimes we have `start_dt` and others `start_date`
- sometimes we have `user_ids` and others `participants_ids`

We need to be consistent with the names of the parameters.

**Comment by dado93** [comment]
My proposal:

- always use `start_date` and `end_date`
- always use `user_id`

**Comment by Vaeliss** [comment]
Closed by 49d84777df1d37d703b24560e47e2609c8b7dbc5
